/* generated by dia/codegen.py */
/*(NULL)*/
class Parc 
{
public:
	Parc (Liste<Location> listeVehicule);
	Parc ();
	~Parc ();
	void ajouterVehicule (Location vehicule);
	void supprimerVehicule (Location vehicule);
	void modifierVehicule (Location vehicule);
	Location rechercherVehicule ();
	void afficherParc (Date dateDebut,
	                   Date dateFin);
	void afficherLoues (Date dateDebut,
	                    Date dateFin);
	void afficherDisponibles (Date dateDebut,
	                          Date dateFin);
private:
	Liste<Location> listeVehicule;
};
